### ISSUE TITLE
P1.1a — Implement stable native WhatsApp domain model and mapper

### ISSUE THREAD

**Issue by MMatlacz** [MMatlacz/Whatsapp#68]
## Goal
Implement the CI-validatable portion of #8 without claiming the still-blocked live transport dependency in #7.

## Scope
- Define transport-independent Swift domain types for `Chat`, `Participant`, `Message`, `MessageCursor`, `Quote`, media metadata, and translation metadata.
- Use explicit strongly typed WhatsApp/chat/message/sender identifiers rather than raw `String` values at higher layers.
- Keep the domain model independent of WebKit, JavaScript bridge envelopes, and WhatsApp Web implementation details.
- Add one explicit transport→domain mapping boundary from the stable transport DTOs introduced in #66.
- Preserve cursor/pagination semantics with strongly typed domain cursors/pages.
- Add deterministic host-independent XCTest coverage for mapping, identifier preservation, quote/media handling, pagination/cursors, translation metadata, and rejection/handling of invalid domain input where applicable.
- Compile the exact production domain source in both the Swift package and iOS application target.

## Acceptance criteria
- Production iOS target compiles the domain model and mapper.
- Domain types compile independently of WebKit and WhatsApp internals.
- Higher-layer domain types do not expose transport DTO types or JavaScript bridge types.
- Transport DTOs map into domain types at one explicit boundary.
- Cursor/pagination contract is strongly typed.
- Tests run via `swift test --package-path native-ios` without simulator, network, credentials, or physical device.
- Parent #8 remains open because its declared dependency #7 is still open.
- Parent #7 remains open for concrete WhatsAppWebTransport/live-message acceptance.

## Parent
Related to #8.
Related to #7.

## Scope boundary
This issue does not implement concrete WebKit transport behavior, receive a real WhatsApp message, or satisfy any physical-device acceptance criterion.
